export const ImagePath = {
  backgroundLoginImage: require('../assets/images/backgroundLogin.png'),
  doctorImage: require('../assets/images/doctorImg.png'),
  profileImage: require('../assets/images/profile.png'),
  homeBackgroundImage: require('../assets/images/homeBackgroundImg.png'),
  bookAppointmentImage: require('../assets/images/BookAppointment.png'),
  InstantVideoConsultImage: require('../assets/images/InstantVideoConsult.png'),
  insuranceImage: require('../assets/images/Insurance.png'),
  labTestImage: require('../assets/images/LabTest.png'),
  upcomingAppointmentImage: require('../assets/images/UpcomingAppointment.png'),
  group: require('../assets/images/Group.png'),
  text: require('../assets/images/text.png'),
  cross: require('../assets/images/cross.png'),
  dentist: require('../assets/images/dentist.png'),
  eprescription: require('../assets/images/eprescription.png'),
  bellBg: require('../assets/images/bellBg1.png'),
  notificationUnread: require('../assets/images/notificationUnread.png'),
  gradientBg: require('../assets/images/gradientBg.png'),
  dr1: require('../assets/images/dr1.png'),
  dr2: require('../assets/images/dr2.png'),
  dr3: require('../assets/images/dr3.png'),
  dr4: require('../assets/images/dr4.png'),
  dr5: require('../assets/images/dr5.png'),
  stars: require('../assets/images/stars.png'),
  famMem1: require('../assets/images/famMem1.png'),
  famMem2: require('../assets/images/famMem2.png'),
  InsCardFront: require('../assets/images/InsCardFront.png'),
  InsCardBack: require('../assets/images/InsCardBack.png'),
  demographics: require('../assets/images/demographics.png'),
  bp: require('../assets/images/bp.png'),
  heartrate: require('../assets/images/heartrate.png'),
  resprate: require('../assets/images/resprate.png'),
  bloodglucose : require('../assets/images/bloodglucose.png'),
  temperature : require('../assets/images/temperature.png'),
  oxysaturation : require('../assets/images/oxysaturation.png'),
  vaccine : require('../assets/images/vaccine.png'),
  uploadimage : require('../assets/images/uploadimage.png'),
  takeimage : require('../assets/images/takeimage.png'),
  noresult : require('../assets/images/NoResult.png'),
};
